### ISSUE TITLE
MacOS: package expansion to the working directory can cause subsequent failures

### ISSUE THREAD

**Issue by bdellegrazie** [MetricMike/asdf-awscli#14]
**Describe the bug**

MacOS
In https://github.com/MetricMike/asdf-awscli/blob/ec4ccdc06ebd34feccf4957e2d2ad647c4d18a2c/lib/utils.bash#L71
package expansion is performed into the current working directory to a _fixed_ directory.

Should a previous install have failed for any reason, as did on one of our systems, this directory is not cleaned up and pkgutil will refuse to expand the package into an existing directory with a slightly cryptic (but perfectly valid) error message:
```
Could not unarchive /Users/<elided>/.asdf/installs/awscli/2.4.6/awscli-2.4.6.pkg (The operation couldn't be completed. File exists)
```
The problem is the directory it is actually talking about is in the working directory where the package will be expanded, not in the installs subdir of asdf.

Suggestion - perhaps expand to a temp directory that is deleted via trap if there's a failure?

**Steps to reproduce**

1. in the current directory, create a directory called AWSCLIV2 - this is to simulate the failure of a prior installation
```mkdir AWSCLIV2```
2. attempt to install using asdf (any v2 should have the same behaviour):
```asdf install awscli 2.4.6``

**Expected behavior**

Installs as expected

**Screenshots**

Errors as described above

**Additional context**
N/A

**Comment by zzztimbo** [comment]
I encountered the same issue just now.
