### ISSUE TITLE
Support for arm64 / apple m1 chips?

### ISSUE THREAD

**Issue by djcp** [MetricMike/asdf-awscli#15]
**Is your feature request related to a problem? Please describe.**

We would love to be able to use `asdf` to distribute specific versions of `awscli` to our users, however, we're now in a mix of architectures including the new m1 chips.  I'd rather not have my users need a mix of homebrew and `asdf` to set up dependencies.

**Describe the solution you'd like**

Seamless support for m1/arm64 chips

Thanks for your consideration!

**Comment by fragolinux** [comment]
Hi, same problems here... I completely removed and readded the plug-in, still getting wrong version

```
❯ asdf uninstall awscli
❯ aws version
No aws executable found for awscli 2.6.3
❯ which aws
/Users/fragolinux/.asdf/shims/aws
❯ asdf plugin remove awscli
❯ which aws
aws not found
❯ aws
zsh: command not found: aws
❯ asdf plugin add awscli
updating plugin repository...HEAD is now at fe90d7a feat: add asdf-gcc-arm-none-eabi plugin (#565)
❯ asdf global awscli latest
version 2.6.3 is not installed for awscli
❯ asdf install awscli latest
awscli 2.6.3 installation was successful!
❯ aws version
/Users/fragolinux/.asdf-code/lib/commands/command-exec.bash: line 28: /Users/fragolinux/.asdf/installs/awscli/2.6.3/bin/aws: Bad CPU type in executable
/Users/fragolinux/.asdf-code/lib/commands/command-exec.bash: line 28: /Users/fragolinux/.asdf/installs/awscli/2.6.3/bin/aws: Undefined error: 0
❯ file $(asdf which aws)
/Users/fragolinux/.asdf/installs/awscli/2.6.3/bin/aws: Mach-O 64-bit executable x86_64

```

**Comment by fragolinux** [comment]
I just made a [PR](https://github.com/MetricMike/asdf-awscli/pull/16) adding support for M1, tested successfully

**Comment by MetricMike** [comment]
Hmm, yeah it appears that the current method (using `pkgutil`) isn't "activating" rosetta. According to #16 though, using `installer` does, but I'd like a second confirmation since https://github.com/github/roadmap/issues/528 probably won't be here for a while before switching methods.

https://github.com/aws/aws-cli/issues/6689 is tracking a source distribution that can be installed in pip. I might consider switching to that method for m1 users when that's released, but not sure yet.

**Comment by fragolinux** [comment]
I've tested successfully my PR, I can make an asciicast showing it, or a video, if you want

**Comment by fragolinux** [comment]
hi, i integrated your latest changes into my branch, please revisit my PR

**Comment by shawnzam** [comment]
Any update on this PR?

**Comment by nlamirault** [comment]
Hi 
any news on this PR? Install AWS CLI using Homebrew works fine, but I would like to manage the cli using asdf.

**Comment by MattDelac** [comment]
> Hi any news on this PR? Install AWS CLI using Homebrew works fine, but I would like to manage the cli using asdf.

Same question here. Any news in March 2023?

**Comment by MetricMike** [comment]
Hi, again sorry for the delay here.

This method in #16 is only triggering the installer to request a Rosetta terminal during installation, while still providing an x86_64 binary no different than the current commit in main. Further, Apple Silicon has severely restricted unattended installations and this does not work on gui-less installations without a user present to accept prompts.

https://github.com/MetricMike/asdf-awscli/pull/21 and/or a future #22 PR will include the AWS official method for source-installation (for v2), similar to homebrew's method

**Comment by MetricMike** [comment]
#21 has been merged with support for building from source and compiles an arm64 very similar

Alternatively, install rosetta 2 and you can continue using the bundled installer and x86_64 binary

**Comment by shawnzam** [comment]
How can I use an `arm64` version? It still installed the `x86_64` version by default.

```shell
 zamechek@zaM1 $ asdf plugin update --all  
... 
 zamechek@zaM1 $ asdf install awscli latest 
asdf-awscli 2.11.15 installation was successful!
 zamechek@zaM1 $ asdf global awscli 2.11.15
 zamechek@zaM1 $ aws --version             
aws-cli/2.11.15 Python/3.11.3 Darwin/22.4.0 exe/x86_64 prompt/off```

**Comment by MetricMike** [comment]
> How can I use an `arm64` version? It still installed the `x86_64` version by default.
> 
> ```shell
>  $ asdf plugin update --all  
> ... 
>  $ asdf install awscli latest 
> asdf-awscli 2.11.15 installation was successful!
>  $ asdf global awscli 2.11.15
>  $ aws --version             
> aws-cli/2.11.15 Python/3.11.3 Darwin/22.4.0 exe/x86_64 prompt/off
> ```

To get an arm64 binary, you'll need to build from source. You can trigger a build from source by prepending the version with `ref` like this example from the README:

```shell
# Build and install v2 from from source
asdf install awscli ref:2.11.15
asdf install awscli "ref:$(asdf latest awscli 2)" # 2.11.15
```

**Comment by vincenthsh** [comment]
Anyone else lost on how to install rosetta, the official install method shows this upon installation

```
sudo softwareupdate --install-rosetta
```

might be good to add this to the docs?
