### ISSUE TITLE
How to install plugins with pip?

### ISSUE THREAD

**Issue by angristan** [MetricMike/asdf-awscli#8]
With awscli v1 installed with pip, you can simply `pip install` the plugin.
With awscli v2 installed with homebrew, you can install a plugin with the bundled pip:

```
/usr/local/opt/awscli/libexec/bin/pip install awscli-plugin-endpoint
```

However, is it possible to install a plugin for awscli installed with this asdf plugin? I don't see any bundled pip.

**Comment by MetricMike** [comment]
Short answer, yes it's possible. Longer answer, it depends and homebrew is using a different method that makes supporting plugins easier.

In https://github.com/asdf-vm/asdf-plugins/issues/222 we discussed whether for v2 to build from source (which is what homebrew is doing, and how it gets a bundled pip) or use the prebuilt binaries that come with all batteries included. We opted to go the latter route as relying on a recent python available on the system path can come with other challenges.

The good news is that with v2, I don't think that matters. According to https://awscli.amazonaws.com/v2/documentation/api/latest/topic/config-vars.html#plugins and https://github.com/wbingli/awscli-plugin-endpoint/issues/15, you should be able to install plugins using the `--no-deps` option with your regular python/pip (whether that's ASDF managed or not) and simply point ~/.aws/config to your plugin. For example:

```bash
$ pip install --no-deps awscli-plugin-endpoint
$ pip show awscli-plugin-endpoint

Name: awscli-plugin-endpoint
Version: 0.4
Summary: Endpoint plugin for AWS CLI
Home-page: https://github.com/wbingli/awscli-plugin-endpoint
Author: Wenbing Li
Author-email: wbingli@gmail.com
License: UNKNOWN
Location: /home/metricmike/.asdf/installs/python/3.9.6/lib/python3.9/site-packages
Requires: awscli
Required-by: 
```

so my ~/.aws/config should look like:

```bash
$ cat ~/.aws/config

[default]
region = us-east-1
output = json

[plugins]
cli_legacy_plugin_path = /home/metricmike/.asdf/installs/python/3.9.6/lib/python3.9/site-packages
endpoint = awscli_plugin_endpoint
```

I don't _think_ it matters if the awscli python version (currently 3.8 for 2.2.22) and the plugin python version (3.9.6 in this example) matter, but it's something to be aware of.



For v1, I would probably recommend not using this tool, as all I'm doing is creating a virtualenv and pip installing awscli there (see https://github.com/MetricMike/asdf-awscli/blob/main/lib/utils.bash#L107-L114).
